### ISSUE TITLE
Polygon all_tickers() returns empty list

### ISSUE THREAD

**Issue by aagnone3** [alpacahq/Momentum-Trading-Example#1]
I have only edited the example to use my paper trading credentials.

`api.polygon.all_tickers()` is returning `{'count': 0, 'status': 'OK', 'tickers': []}` for my paper credentials. Any idea why this might be? I have a bank account linked and some money transferred, so I _believe_ I have a brokerage account fully set up. That's my main thought on the issue.

Thanks for the help!

**Comment by marianormuro** [comment]
Same problem

**Comment by CruddyShad0w** [comment]
I had this issue during a downtime for the SERVER between 10pm and 2am pst.

**Comment by ttt733** [comment]
Sounds like this is an intermittent Polygon issue. You may want to contact them for more information at support@polygon.io.

**Comment by RMehta95** [comment]
I'm having the same issue. I contacted Polygon and they said the stream is only available when connected to the live trading account and not paper trading account

**Comment by zoakes** [comment]
I’m having same issue — but it DID work for paper previously ? Is it just down right now ? Or what...

**Comment by RMehta95** [comment]
Contrary to what Polygon told me, I actually was able to get the Polygon feed working with my paper account. However, it only started to work after I funded by live trading account with real $.

**Comment by zoakes** [comment]
Got it — yes my Algo is now working too. Seems the server was simply down over the weekend.



On May 10, 2020, at 9:16 PM, Rohan Mehta <notifications@github.com<mailto:notifications@github.com>> wrote:



Contrary to what Polygon told me, I actually was able to get the Polygon feed working with my paper account. However, it only started to work after I funded by live trading account with real $.
