### ISSUE TITLE
404 Not Found Error

### ISSUE THREAD

**Issue by erod998** [alpacahq/Momentum-Trading-Example#16]
Using Python 3.8.2:
`requests.exceptions.HTTPError:` 404 Client Error: Not Found for url: https://api.polygon.io/v1/historic/agg/minute/RDHL?limit=1000&apiKey=mykey`

Any idea what could be causing this?

**Comment by umitanuki** [comment]
Thanks for the report. We will fix the issue by upgrading to v2 endpoint.
