### ISSUE TITLE
Nothing in my account.

### ISSUE THREAD

**Issue by dc500** [alpacahq/Momentum-Trading-Example#27]
I used the Momentum-Trading-Example to test out the API. I'm watching everything play out. I see where I am buying and selling (in the terminal), but nothing is posting to my account. Did I miss something?

Yeah something is not right. I dropped my Equity to $25k which gave me $100k in buying power. When the script starts it says I have Initial total buying power = 361722.36.

**Comment by dc500** [comment]
Fixed it.

**Comment by noahdemoes** [comment]
How were you able to fix it? I am experiencing the same issue.

**Comment by dc500** [comment]
> How were you able to fix it? I am experiencing the same issue.

I got it "working" about a hour ago. It was connecting to the server, but the code was screwed up. 

Describe exactly what's happening for you?

If the code is working properly you will see data being returned in your terminal window. I set mine to run during the premarket. I should know within a hour if it's actually working (buying) or not. Yesterday, it tried to buy on my LIVE but I got hit with a PTD warning  (I didn't liq RH yet lol). 



To make things easier for you, I'll upload what I have. Give me about 2 mins. It will be saved as AP1.

**Comment by dc500** [comment]
> How were you able to fix it? I am experiencing the same issue.

Sorry I took longer than 2 mins. I've uploaded it for you. It's saved as AP1. - [https://github.com/dc500/AP1](link)

**Comment by noahdemoes** [comment]
Thank you for posting that code.
So my output when I run python algo.py is the following:

Getting current ticker data...
Success.
Tracking 151 symbols.
Getting historical data...
1/151
2/151
3/151
4/151
5/151
...
150/151
151/151
Success.
Watching 151 symbols.

There is  nothing that occurs afterward, so there is no buying or selling.

**Comment by russelldouglas** [comment]
@noahdemoes I'm having this exact same problem. Did you ever figure out why it does this or fix it?

**Comment by nickvertucci** [comment]
@noahdemoes @dc500  were you guys able to get it working? I have the same exact issue and not seeing any results. Hopefully someone is still monitoring this repoo and we can all fix it for everyone.
