### ISSUE TITLE
Nothing happens after 'Watching Symbols'

### ISSUE THREAD

**Issue by russelldouglas** [alpacahq/Momentum-Trading-Example#30]
So I've seen this problem in a few places, but have yet to see a fix for it.

Basically, the program runs fine, it doesn't throw any errors or anything like that. It goes through this:

`Getting current ticker data...
Success.
Tracking 102 symbols.
Getting historical data...
1/102
2/102
3/102
4/102
5/102
...
101/102
102/102
Success.
Watching 102 symbols.`

But then nothing happens. It never buys. I saw that it could be if you don't start the program early enough in the morning, because of how it waits 15 minutes after the market opens, but no matter when I start it, it still gets stuck there and never buys.

If anyone has this problem or has a fix for it, that would be great. I will keep working on it, and if I find a fix I will post it. Thanks!

**Comment by russelldouglas** [comment]
I found the problem! So I had updated the 'ta' package to version 0.7.0 instead of 0.4.5 and just changed `from ta import macd` to `from ta.trend import macd`

This worked for a while, but the newest version of macd doesn't have n_fast or n_slow. So I reverted back to 'ta' version 0.4.5 and changed the import back to normal, and everything works now. Just this past hour I'm almost up 2% so we'll see how it goes for the rest of the day.

If you have any questions on ANY problems, not just this one, feel free to ask. I have been through almost every problem on this Github and more and managed to fix them all, and I'd be glad to help with any questions!

**Comment by Lorindal** [comment]
> I found the problem! So I had updated the 'ta' package to version 0.7.0 instead of 0.4.5 and just changed `from ta import macd` to `from ta.trend import macd`
> 
> This worked for a while, but the newest version of macd doesn't have n_fast or n_slow. So I reverted back to 'ta' version 0.4.5 and changed the import back to normal, and everything works now. Just this past hour I'm almost up 2% so we'll see how it goes for the rest of the day.
> 
> If you have any questions on ANY problems, not just this one, feel free to ask. I have been through almost every problem on this Github and more and managed to fix them all, and I'd be glad to help with any questions!

I've worked through a few problems now using recommended fixes. Everything runs now through "watching symbols" -- then I get:

`ERROR:root:error while consuming ws messages: consume cancelled`

Any ideas?

**Comment by nickvertucci** [comment]
> I found the problem! So I had updated the 'ta' package to version 0.7.0 instead of 0.4.5 and just changed `from ta import macd` to `from ta.trend import macd`
> 
> This worked for a while, but the newest version of macd doesn't have n_fast or n_slow. So I reverted back to 'ta' version 0.4.5 and changed the import back to normal, and everything works now. Just this past hour I'm almost up 2% so we'll see how it goes for the rest of the day.
> 
> If you have any questions on ANY problems, not just this one, feel free to ask. I have been through almost every problem on this Github and more and managed to fix them all, and I'd be glad to help with any questions!

Hey Zenwaffles, I've done the same thing you have but still stuck on watching symbols........ Any other updates or ideas you have?

**Comment by nickvertucci** [comment]
@zenwaffles Hope you are still watching this repo :)
