### ISSUE TITLE
ERROR:root:error while consuming ws messages: macd() got an unexpected keyword argument 'n_fast'

### ISSUE THREAD

**Issue by josephfkrause** [alpacahq/Momentum-Trading-Example#35]
Fixed the Mcad issue, now getting this. Im a new coder so sorry if this is easy. Im still learning my way through this code. 

Thank you.

edit: also, im only importing ta, and the using ta.trend.macd instead

**Comment by connor-mcswain** [comment]
Hey, looks like macd from ta.trend changed the argument names. Try replacing n_fast and n_slow with window_fast and window_slow.

**Comment by josephfkrause** [comment]
> Hey, looks like macd from ta.trend changed the argument names. Try replacing n_fast and n_slow with window_fast and window_slow.

Yes, this is solution, I found in function documentation. I was running it today to make sure it worked before closing. Thank you!
