### ISSUE TITLE
"Invalid Syntax" error on start

### ISSUE THREAD

**Issue by briannicholls** [alpacahq/Momentum-Trading-Example#9]
Hey, I'm getting the following error on initialization, can't get it running. Made no changes to the code other than replacing the key, secret etc:
```  File "algo.py", line 120
    async def handle_trade_update(conn, channel, data):
        ^
SyntaxError: invalid syntax
```

**Comment by umitanuki** [comment]
Please use python 3.6 or above. This is a relatively new python syntax.
